[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "WEBBBILO_FRONT_DB"
database_id = "52253618-4e9f-484d-93ee-6962ba5c04ac"
preview_database_id = "DB"
migrations_dir = "./server/db/migrations"
